### PR TITLE
Update to add examples and fix compile problems

### PR DESCRIPTION
**Pull request by Bodmer**
I have forked the develop branch and made changes
Existing examples have not been updated but I have added some new ones specific to TFT_eSPI
Rendering has been speeded up by drawing pixel runs as lines
keywords.txt added
* added for architecture in library.properties so examples appear in IDE menu
* sfnt file updated so library compiles for ESP32 with latest board package (which is picky)

### CODE REVIEW

**Comment by martinberlin** [comment]
Awesome improvement. A before and after video comparison
https://twitter.com/martinfasani/status/1591491026656841730

**Comment by Bodmer** [comment]
The ESP32 board package in the Arduino environment treats some warnings as errors. The commented out function generated a compile warning that the function was "not used" and this was then treated as an error so compile failed. Commenting out the unused funtion fixes this.

**Comment by takkaO** [comment]
@Bodmer 

I can't reproduce the issue in my environment, so please give me the following information.

- Arduino IDE version
- Board manager and version
- Target board
- Minimum code that can be reproduced

Screenshots are also acceptable.
Thank you.

**Comment by Bodmer** [comment]
Arduino IDE version 1.8.13 - but I suspect that does not matter.
ESP Ardunio board package 2.0.5 - loaded via board manager
Error message:
```
D:\xxx\Arduino\Sketches\libraries\OpenFontRender\src\sfnt\ttcmap.c:55:3: error: 'tt_cmap_init' defined but not used [-Werror=unused-function]
   tt_cmap_init( TT_CMap   cmap,
   ^~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
```
The later ESP32 board packages are very picky about unused variables and unused functions.

**Comment by Bodmer** [comment]
I just noticed that my compiler warnings are set to "All":
image


 So the unused function will not be treated as an error if the warnings are set to "Default".

The palform.txt specifies the warning/error level and for the ESP32 it is strict for the "All" setting:

image

**Comment by takkaO** [comment]
@Bodmer 

Thanks for the info.
I was able to reproduce it in my environment (it seems that other errors were masking the desired error 😭).
I also confirmed that the problem can be solved from the Arduino preferences.

This library accepts to change FreeType version, and I think that any modifications to the FreeType code should be made in `ModifyLibs.sh/ps1` script.
Therefore, I think I'll pass that any changes to `sfnt/ttcmap.c` this time.
Other changes will be merged so just a moment, please.

Thank you.

**Comment by Bodmer** [comment]
Yes, I think the change to ttcmap.c is not needed and as you say makes a version change clean.

**Pull request merged**
